### ISSUE TITLE
CSS request and null data

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-world-income-share#1]
@ilyankou 

Would you please make these code revisions if they're simple to do?

1) Change the 'info leaflet-control' to float left, and increase opacity to 0.9

2) How do I add the 'checkNull' function into info.update?

**Comment by ilyankou** [comment]
How does this look?
https://handsondataviz.github.io/leaflet-world-income-share/

**Comment by JackDougherty** [comment]
Fabulous! I followed up on this and made some minor modifications. Thanks!
